Repository ZenBit-Tech/CodeCrafters_fe, pull requests merged in 2024-12, with the labels that each got.

#37 Feat/assign orders logic
  README.md
  index.html
  src/constants/colors.ts
  src/constants/dateFormats.ts
  src/constants/numbers.ts
  src/pages/CompanyListPage/index.tsx
  src/pages/CreateRoute/DriversStage/useChoseDriver.ts
  src/pages/CreateRoute/RouteManagement/api/getRoutesData.ts
  src/pages/CreateRoute/RouteManagement/components/InformBlock/components/UnassignedOrder/index.tsx
  src/pages/CreateRoute/RouteManagement/components/InformBlock/components/UnassignedOrder/styles.ts
  src/pages/CreateRoute/RouteManagement/components/InformBlock/index.tsx
  src/pages/CreateRoute/RouteManagement/components/InformBlock/useDragEnd.ts
  src/pages/CreateRoute/RouteManagement/index.tsx
  src/pages/CreateRoute/SecondStage/useChangeDate.ts
  src/pages/SignIn/index.tsx
  src/store/slices/ordersToDriversSlice.ts
  src/utils/createTimeRange.ts
  src/utils/i18n.ts
Labels: enhancement, invalid

#38 Feat/add driver fe
  src/components/ModalForm/index.tsx
  src/components/SearchComponent/styles.ts
  src/constants/constants.ts
  src/constants/validation.ts
  src/pages/CreateRoute/DriversStage/api/getDrivers.ts
  src/pages/CreateRoute/DriversStage/components/DriverForm/index.tsx
  src/pages/CreateRoute/DriversStage/components/DriverForm/useDriverForm.ts
  src/pages/CreateRoute/DriversStage/index.tsx
  src/pages/CreateRoute/DriversStage/styles.ts
  src/pages/CreateRoute/DriversStage/useGetDrivers.ts
  src/utils/i18n.ts
Labels: enhancement

#35 Feat/route details UI
  src/constants/days.ts
  src/hooks/useToggleVisible.ts
  src/interfaces/interfaces.ts
  src/main.tsx
  src/pages/CreateRoute/RouteManagement/api/getRoutesData.ts
  src/pages/RouteDetails/components/Map/RoutingComponent.tsx
  src/pages/RouteDetails/components/Map/index.tsx
  src/pages/RouteDetails/components/Map/styles.css
  src/pages/RouteDetails/components/Map/styles.ts
  src/pages/RouteDetails/components/RouteDetailsControlBtns/index.tsx
  src/pages/RouteDetails/components/RouteDetailsControlBtns/styles.ts
  src/pages/RouteDetails/components/RouteInform/api/getRouteDetails.ts
  src/pages/RouteDetails/components/RouteInform/components/DriverBlock/index.tsx
  src/pages/RouteDetails/components/RouteInform/components/DriverBlock/styles.ts
  src/pages/RouteDetails/components/RouteInform/components/OrderDetails/index.tsx
  src/pages/RouteDetails/components/RouteInform/components/OrderDetails/styles.ts
  src/pages/RouteDetails/components/RouteInform/index.tsx
  src/pages/RouteDetails/components/RouteInform/styles.ts
  src/pages/RouteDetails/index.tsx
  src/pages/RouteDetails/styles.ts
  src/pages/RouteDetails/useGetRoute.ts
  src/pages/RouteDetails/useViewPin.ts
  src/routes/router.tsx
  src/utils/createIdString.ts
  src/utils/generateRandomColor.ts
  src/utils/i18n.ts
Labels: enhancement

#41 Feat/navbar by roles fe
  src/components/Layout/RootLayout/index.tsx
  src/components/Layout/RootLayout/useRootLayout.tsx
  src/components/NavigationCount/index.tsx
  src/components/NavigationCount/styles.ts
  src/constants/roles.ts
  src/pages/Orders/api/getOrders.ts
  src/routes/router.tsx
Labels: enhancement

#31 feat: connect team management page to backend
  package-lock.json
  package.json
  src/api/userActions.ts
  src/assets/assets.ts
  src/components/CompanyItem/index.tsx
  src/components/DriverInfoCard/index.tsx
  src/components/ModalForm/index.tsx
  src/components/OrderRow/index.tsx
  src/components/RoutesRow/index.tsx
  src/components/UserAvatar/index.tsx
  src/components/UserRow/index.tsx
  src/pages/CreateRoute/DriversStage/components/DriverCard/index.tsx
  src/pages/CreateRoute/RouteManagement/components/RouteDetails/RouteDetails.tsx
  src/pages/CreateRoute/SecondStage/components/OrderManagementCard/index.tsx
  src/pages/Orders/components/OrderItem/OrderItem.tsx
  src/pages/RouteDetails/components/RouteInform/components/DriverBlock/index.tsx
  src/pages/TeamManagment/UserForm/UserForm.tsx
  src/pages/TeamManagment/UserForm/styles.ts
  src/pages/TeamManagment/UserForm/useUserForm.tsx
  src/pages/TeamManagment/index.tsx
  src/pages/TeamManagment/types.ts
  src/pages/TeamManagment/useFetchUsers.tsx
  src/pages/TeamManagment/useUserFilters.tsx
  src/pages/components/AdminListTable/index.tsx
  src/routes/router.tsx
  src/services/usersService.ts
  src/store/persistConfig.ts
  src/store/slices/authSlice.ts
  src/utils/axiosInstance.ts
  src/utils/i18n.ts
  src/utils/nameUtils.ts
  tsconfig.app.tsbuildinfo
Labels: enhancement

#46 Fix/add loaders
  src/api/adminActions.ts
  src/api/userActions.ts
  src/pages/CompanyListPage/CompanyForm/CompanyForm.tsx
  src/pages/CreateRoute/DateManagment/Calendar/useMarkDates.tsx
  src/pages/CreateRoute/DriversStage/api/getDrivers.ts
  src/pages/CreateRoute/RouteManagement/api/getRoutesData.ts
  src/pages/Orders/api/getOrders.ts
  src/pages/RouteDetails/components/RouteInform/api/getRouteDetails.ts
  src/pages/RouteDetails/useViewPin.ts
  src/pages/SignIn/useSignIn.ts
  src/pages/TeamManagment/UserForm/useUserForm.tsx
  src/pages/TeamManagment/useFetchUsers.tsx
Labels: enhancement, invalid

#44 Feat/route list calendar
  package-lock.json
  package.json
  src/assets/icons/calendar-arr-left.svg
  src/assets/icons/calendar-arr-right.svg
  src/components/CalendarRange/index.tsx
  src/components/CalendarRange/style.css
  src/components/CalendarRange/styles.ts
  src/components/CalendarRange/useCalendarRange.ts
  src/constants/colors.css
  src/constants/dateFormats.ts
Labels: enhancement

#48 + Add: date verification logic
  package-lock.json
  src/assets/assets.ts
  src/assets/codecrafters.png
  src/assets/logo-one.svg
  src/pages/CreateRoute/RouteManagement/components/Map/RoutingComponent.tsx
  src/pages/CreateRoute/SecondStage/useChangeDate.ts
  src/pages/RouteDetails/components/Map/RoutingComponent.tsx
  tsconfig.app.tsbuildinfo
Labels: bug, invalid

#50 fix: add close feature to cancel button
  src/pages/CompanyListPage/CompanyForm/CompanyForm.tsx
  src/pages/components/AdminForm/index.tsx
  src/pages/components/AdminForm/useAdminForm.ts
Labels: bug

#49 fix: remove logo constant from code
  src/api/adminActions.ts
  src/constants/constants.ts
  src/interfaces/AdminList/index.ts
  src/pages/CreateRoute/DriversStage/api/getDrivers.ts
Labels: bug

#54 Feat/no routes create
  src/api/routesActions.ts
  src/components/CalendarRange/styles.ts
  src/components/CalendarRange/useCalendarRange.ts
  src/interfaces/Routes/index.ts
  src/pages/Routes/components/FilterHeader/index.tsx
  src/pages/Routes/components/FilterHeader/useFilterHeader.ts
  src/pages/Routes/components/NoRoutesMessage/index.tsx
  src/pages/Routes/components/NoRoutesMessage/styles.ts
  src/pages/Routes/index.tsx
  src/pages/Routes/useRoutes.ts
  src/utils/i18n.ts
Labels: enhancement

#51 Fix navbar new orders numbers
  src/components/Layout/RootLayout/index.tsx
  src/components/NavigationCount/index.tsx
  src/components/NavigationCount/styles.ts
Labels: bug, enhancement

#55 + Configure: Jest
  eslint.config.js
  jest.config.ts
  package-lock.json
  package.json
  src/global.d.ts
  src/test/componentForTest/Person.css
  src/test/componentForTest/Person.test.tsx
  src/test/componentForTest/Person.tsx
  src/test/componentForTest/logo-one.svg
  tsconfig.app.json
  tsconfig.json
Labels: enhancement

#56 Fix/orders plust route creating
  src/components/SearchComponent/index.tsx
  src/components/SearchComponent/useHandleKeyDown.ts
  src/pages/CreateRoute/RouteManagement/components/RouteDetails/RouteDetails.tsx
  src/pages/CreateRoute/RouteManagement/useCreateRoutes.ts
  src/pages/Orders/components/SortingRow/styles.ts
Labels: bug, invalid

#58 Fix/user add error message
  src/pages/TeamManagment/UserForm/useUserForm.tsx
  src/pages/TeamManagment/useFetchUsers.tsx
Labels: bug

#59 fix: change icon path to absolute one
  src/components/UserRow/index.tsx
  src/pages/TeamManagment/UserForm/UserForm.tsx
Labels: bug

#57 Feat/expiration modal fe
  src/api/adminActions.ts
  src/api/userActions.ts
  src/components/TokenExpiredModal/index.tsx
  src/components/TokenExpiredModal/styles.ts
  src/components/TokenExpiredModal/useTokenExpiredModal.ts
  src/constants/constants.ts
  src/routes/router.tsx
  src/store/persistConfig.ts
  src/store/slices/authSlice.ts
  src/store/slices/tokenModalSlice.ts
  src/store/store.ts
  src/utils/axiosInstance.ts
  src/utils/i18n.ts
Labels: enhancement

#61 Feat/statuses management
  src/components/Status/index.tsx
  src/constants/status.ts
  src/interfaces/interfaces.ts
  src/pages/Orders/components/OrderItem/OrderItem.tsx
Labels: enhancement

#63 * Fix: TS build errors
  src/components/SearchComponent/index.tsx
  src/store/slices/chosePinSlice.ts
  src/store/slices/choseRouteSlice.ts
  src/store/slices/choseRoutes.ts
  src/store/slices/createRouteSlice.ts
  src/store/slices/driversSlice.ts
  src/store/slices/exampleSlice.ts
  src/store/slices/ordersPageSlice.ts
  src/store/slices/ordersToDriversSlice.ts
  src/store/slices/routesSlice.ts
  src/store/slices/sortDriversSlice.ts
  src/store/slices/tokenModalSlice.ts
Labels: bug, invalid

#64 * Change: tsconfig files
  tsconfig.app.json
  tsconfig.node.json
Labels: bug, invalid

#60 feat: add appropriate text when users not found
  src/components/ConditionalWrapper/index.tsx
  src/components/ConditionalWrapper/styles.ts
  src/pages/TeamManagment/UserForm/styles.ts
  src/pages/TeamManagment/index.tsx
  src/utils/i18n.ts
Labels: bug, enhancement
