Repository ZenBit-Tech/CodeCrafters_fe, pull requests merged in 2024-11, with the labels that each got.

#3 Feature/login
  index.html
  package-lock.json
  package.json
  src/assets/login/key.png
  src/assets/login/lock.png
  src/assets/login/logo.svg
  src/assets/react.svg
  src/constants/colors.ts
  src/main.tsx
  src/pages/ExamplePage/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignIn/styles.ts
  src/pages/SignIn/useSignIn.ts
  src/pages/components/LoginLogo/index.tsx
  src/pages/components/LoginLogo/styles.ts
  src/routes/router.tsx
  src/theme.ts
  src/utils/i18n.ts
  tsconfig.app.json
  vite.config.ts
Labels: enhancement

#5 Feature/fe-be-signin
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/components/ExampleComponent/useExampleComponent.tsx
  src/main.tsx
  src/pages/Orders/index.tsx
  src/pages/SignIn/useSignIn.ts
  src/pages/components/ProtectedRoute/index.tsx
  src/routes/router.tsx
  src/store/persistConfig.ts
  src/store/slices/authSlice.ts
  src/store/slices/exampleSlice.ts
  src/store/store.ts
  src/utils/axiosInstance.ts
  src/utils/history.ts
  src/utils/i18n.ts
Labels: enhancement

#2 feat(ui-kit): add new reusable components
  src/components/BasicDatePicker/index.tsx
  src/components/Button/index.tsx
  src/components/CalendarRange/index.tsx
  src/components/Checkbox/index.tsx
  src/components/DetailedRouteRow/index.tsx
  src/components/DriverAvatar/index.tsx
  src/components/DriverInfoCard/index.tsx
  src/components/DriverRouteInfo/index.tsx
  src/components/OrderRow/index.tsx
  src/components/PopupMessage/index.tsx
  src/components/RoutesRow/index.tsx
  src/components/Status/index.tsx
  src/components/TextInput/index.tsx
  src/components/TopRow/index.tsx
  src/constants/font.ts
  src/constants/status.ts
  src/main.tsx
  src/pages/ExamplePage/index.tsx
  src/theme.ts
Labels: enhancement

#7 feat(layout): integrate new layout structure with reusable components
  .eslintrc.json
  package-lock.json
  package.json
  src/assets/Logo-1.svg
  src/assets/Logo-2.svg
  src/assets/assets.ts
  src/components/Layout/DashboardLayout/index.tsx
  src/components/Layout/RootLayout/index.tsx
  src/constants/colors.ts
  src/pages/DashboardPage/index.tsx
  src/pages/ExamplePage/index.tsx
  src/routes/router.tsx
  src/theme.ts
  src/utils/i18n.ts
Labels: enhancement

#12 Feature/sign in
  package-lock.json
  package.json
  src/App.tsx
  src/api/userActions.ts
  src/components/Layout/RootLayout/index.tsx
  src/interfaces/SignIn/index.ts
  src/main.tsx
  src/pages/ExamplePage/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/NotFound/styles.ts
  src/pages/SignIn/index.tsx
  src/pages/SignIn/useSignIn.ts
  src/pages/components/ProtectedRoute/index.tsx
  src/pages/components/TextInputRef/index.tsx
  src/routes/router.tsx
  src/store/persistConfig.ts
  src/store/slices/authSlice.ts
  src/store/store.ts
  src/theme.ts
  src/utils/axiosInstance.ts
  src/utils/i18n.ts
Labels: enhancement

#15 Fix/login vaildation
  src/pages/SignIn/useSignIn.ts
Labels: bug

#17 Feat/orders page
  src/App.tsx
  src/assets/icons/search.svg
  src/components/Loader/Loader.tsx
  src/components/Loader/styles.css
  src/constants/colors.css
  src/constants/colors.ts
  src/constants/moths.ts
  src/constants/ordersSorts.ts
  src/interfaces/interfaces.ts
  src/main.tsx
  src/pages/Orders/api/getOrders.ts
  src/pages/Orders/components/OrderItem/OrderItem.tsx
  src/pages/Orders/components/OrderItem/styles.ts
  src/pages/Orders/components/OrderItem/types.ts
  src/pages/Orders/components/SearchOrders/index.tsx
  src/pages/Orders/components/SearchOrders/styles.ts
  src/pages/Orders/components/SearchOrders/useSearch.ts
  src/pages/Orders/components/SortingRow/SortingRow.tsx
  src/pages/Orders/components/SortingRow/styles.ts
  src/pages/Orders/components/SortingRow/useSortOrders.ts
  src/pages/Orders/index.tsx
  src/pages/Orders/styles.ts
  src/pages/Orders/useOrdersPagination.ts
  src/store/slices/loaderSlice.ts
  src/store/slices/ordersPageSlice.ts
  src/store/store.ts
Labels: enhancement

#20 * Fix: event unused var
  src/pages/Orders/index.tsx
Labels: bug

#21 Feat/date managment page
  package-lock.json
  package.json
  src/assets/icons/arrow-left.svg
  src/assets/icons/arrow-right.svg
  src/assets/icons/calendar-icon.svg
  src/assets/icons/luggage-icon-active.svg
  src/assets/icons/luggage-icon.svg
  src/assets/icons/people-icon-active.svg
  src/assets/icons/people-icon.svg
  src/assets/icons/route-pin-active-icon.svg
  src/assets/icons/route-pin-icon.svg
  src/components/ExampleComponent/index.tsx
  src/components/ExampleComponent/styles.ts
  src/components/ExampleComponent/useExampleComponent.tsx
  src/pages/DateManagment/Calendar/index.tsx
  src/pages/DateManagment/Calendar/styles.css
  src/pages/DateManagment/Calendar/useMarkDates.tsx
  src/pages/DateManagment/index.tsx
  src/pages/ExamplePage/index.tsx
  src/pages/ExamplePage/styles.ts
  src/pages/components/CreateRouteBtns/index.tsx
  src/pages/components/CreateRouteBtns/styles.ts
  src/pages/components/CreateRouteProgressBar/FirstStep/index.tsx
  src/pages/components/CreateRouteProgressBar/FourStep/index.tsx
  src/pages/components/CreateRouteProgressBar/SecondStep/index.tsx
  src/pages/components/CreateRouteProgressBar/ThirdStep/index.tsx
  src/pages/components/CreateRouteProgressBar/index.tsx
  src/pages/components/CreateRouteProgressBar/styles.ts
  src/routes/router.tsx
Labels: enhancement

#19 feat: Company crud
  src/components/CompanyItem/index.tsx
  src/components/DriverAvatar/index.tsx
  src/components/ModalForm/index.tsx
  src/components/ModalForm/styles.ts
  src/pages/CompanyListPage/CompanyForm/CompanyForm.tsx
  src/pages/CompanyListPage/CompanyForm/styles.css
  src/pages/CompanyListPage/CompanyForm/styles.ts
  src/pages/CompanyListPage/index.tsx
  src/pages/CompanyListPage/useCompanies.tsx
  src/utils/i18n.ts
Labels: enhancement

#18 Feature/admin crud
  src/App.tsx
  src/api/adminActions.ts
  src/components/ModalForm/index.tsx
  src/components/ModalForm/styles.ts
  src/constants/constants.ts
  src/interfaces/AdminList/index.ts
  src/main.tsx
  src/pages/AdminList/index.tsx
  src/pages/AdminList/useAdminList.ts
  src/pages/CompanyListPage/CompanyForm/CompanyForm.tsx
  src/pages/CompanyListPage/index.tsx
  src/pages/components/AdminForm/index.tsx
  src/pages/components/AdminForm/styles.ts
  src/pages/components/AdminForm/useAdminForm.ts
  src/pages/components/AdminListTable/index.tsx
  src/pages/components/DeleteAdmin/index.tsx
  src/pages/components/DeleteAdmin/styles.ts
  src/pages/components/DeleteAdmin/useDeleteAdmin.ts
  src/routes/router.tsx
  src/utils/axiosInstance.ts
  src/utils/i18n.ts
Labels: enhancement

#24 * Fix: get dates logic
  src/pages/DateManagment/Calendar/index.tsx
  src/pages/DateManagment/Calendar/useMarkDates.tsx
Labels: invalid

#26 fix(modal): close modal on successful admin addition or update
  src/pages/CompanyListPage/CompanyForm/CompanyForm.tsx
Labels: enhancement

#25 Fix/update admin list
  src/api/adminActions.ts
  src/constants/constants.ts
  src/interfaces/AdminList/index.ts
  src/pages/AdminList/index.tsx
  src/pages/AdminList/useAdminList.ts
  src/pages/components/AdminListTable/index.tsx
Labels: enhancement

#27 feat: add company input
  src/api/adminActions.ts
  src/components/CompanyItem/index.tsx
  src/interfaces/AdminList/index.ts
  src/pages/AdminList/index.tsx
  src/pages/CompanyListPage/CompanyForm/CompanyForm.tsx
  src/pages/components/AdminSideBar/index.tsx
  src/pages/components/AdminSideBar/useAdminSideBar.ts
  src/utils/i18n.ts
Labels: enhancement

#28 Feat/four stage page
  .env.example
  package-lock.json
  package.json
  src/assets/icons/drop-down-icon.svg
  src/assets/icons/eye.svg
  src/assets/icons/map-pin.svg
  src/assets/icons/note.svg
  src/constants/colors.ts
  src/pages/CreateRoute/RouteManagement/components/InformBlock/index.tsx
  src/pages/CreateRoute/RouteManagement/components/InformBlock/styles.ts
  src/pages/CreateRoute/RouteManagement/components/Map/RoutingComponent.tsx
  src/pages/CreateRoute/RouteManagement/components/Map/index.tsx
  src/pages/CreateRoute/RouteManagement/components/Map/styles.css
  src/pages/CreateRoute/RouteManagement/components/RouteDetails/index.tsx
  src/pages/CreateRoute/RouteManagement/components/RouteDetails/styles.ts
  src/pages/CreateRoute/RouteManagement/index.tsx
  src/pages/CreateRoute/RouteManagement/styles.ts
  src/pages/Orders/api/getOrders.ts
  src/pages/Orders/components/OrderItem/OrderItem.tsx
  src/routes/router.tsx
Labels: enhancement

#32 refactor(error): added more informative description for error fail
  src/utils/i18n.ts
Labels: enhancement

#30 Feature/routes list UI
  src/assets/icons/jump-rope.svg
  src/components/RoutesRow/index.tsx
  src/components/Status/index.tsx
  src/constants/routes.ts
  src/interfaces/Routes/index.ts
  src/pages/Routes/components/ActionsPanel/index.tsx
  src/pages/Routes/components/FilterHeader/index.tsx
  src/pages/Routes/components/Pagination/index.tsx
  src/pages/Routes/components/RouteTable/index.tsx
  src/pages/Routes/index.tsx
  src/pages/Routes/styles.ts
  src/pages/Routes/useRoutes.ts
  src/routes/router.tsx
  src/utils/i18n.ts
Labels: enhancement

#33 feat: add ability to add new companies to the beginning of the compan…
  src/pages/CompanyListPage/CompanyForm/CompanyForm.tsx
  src/pages/CompanyListPage/index.tsx
  src/pages/CompanyListPage/useCompanies.tsx
Labels: enhancement
