Repository ZenBit-Tech/CodeCrafters_fe, pull requests merged in 2025-01, with the labels that each got.

#65 Fix/router
  src/components/CalendarRange/styles.ts
  src/components/Layout/RootLayout/index.tsx
  src/components/RedirectBasedOnRole/index.tsx
  src/components/RoutesRow/index.tsx
  src/pages/RouteDetails/components/RouteDetailsControlBtns/index.tsx
  src/pages/RouteDetails/components/RouteDetailsControlBtns/useDeleteRoute.ts
  src/pages/Routes/components/ActionsPanel/index.tsx
  src/pages/Routes/components/ActionsPanel/styles.ts
  src/pages/Routes/components/FilterHeader/index.tsx
  src/pages/Routes/components/FilterHeader/styles.ts
  src/pages/Routes/components/RouteTable/index.tsx
  src/pages/Routes/components/RouteTable/styles.ts
  src/pages/Routes/styles.ts
  src/routes/router.tsx
Labels: bug, enhancement

#68 Fix/bugs create route
  src/App.tsx
  src/pages/CreateRoute/DriversStage/components/DriverCard/index.tsx
  src/pages/CreateRoute/DriversStage/components/DriverCard/styles.ts
  src/pages/CreateRoute/RouteManagement/components/RouteDetails/RouteDetails.tsx
  src/pages/CreateRoute/SecondStage/index.tsx
  src/pages/Orders/index.tsx
  src/pages/components/EmptyOrdersComponent/index.tsx
  src/pages/components/EmptyOrdersComponent/styles.ts
Labels: bug, invalid

#67 feat: added all select checkbox for second stage orders
  src/pages/CreateRoute/RouteManagement/useCreateRoutes.ts
  src/pages/CreateRoute/SecondStage/components/OrderManagementCard/useChooseOrder.ts
  src/pages/CreateRoute/SecondStage/components/OrdersManagementSort/index.tsx
  src/pages/CreateRoute/SecondStage/components/OrdersManagementSort/styles.ts
  src/pages/CreateRoute/SecondStage/components/OrdersManagementSort/useSortOrders.ts
  src/pages/CreateRoute/SecondStage/index.tsx
  src/pages/CreateRoute/SecondStage/useOrdersPagination.ts
  src/store/slices/createRouteSlice.ts
Labels: enhancement

#62 Feat/connect notifications
  src/api/routesActions.ts
  src/components/CalendarRange/index.tsx
  src/components/CalendarRange/useCalendarRange.ts
  src/components/ConditionalWrapper/index.tsx
  src/components/RoutesRow/index.tsx
  src/components/RoutesRow/styles.ts
  src/components/RoutesRow/useRoutesRow.ts
  src/components/Status/index.tsx
  src/constants/colors.ts
  src/constants/constants.ts
  src/constants/dateFormats.ts
  src/interfaces/Routes/index.ts
  src/interfaces/interfaces.ts
  src/pages/RouteDetails/components/RouteInform/components/OrderDetails/index.tsx
  src/pages/RouteDetails/components/RouteInform/components/OrderDetails/styles.ts
  src/pages/RouteDetails/components/RouteInform/index.tsx
  src/pages/Routes/components/ActionsPanel/index.tsx
  src/pages/Routes/components/ActionsPanel/useActionsPanel.ts
  src/pages/Routes/components/FilterHeader/useFilterHeader.ts
  src/pages/Routes/components/RouteDetailsModal/index.tsx
  src/pages/Routes/components/RouteDetailsModal/styles.ts
  src/pages/Routes/index.tsx
  src/pages/Routes/styles.ts
  src/pages/Routes/useRoutes.ts
  src/theme.ts
  src/utils/formatStatus.test.ts
  src/utils/formatStatus.ts
  src/utils/i18n.ts
Labels: bug, enhancement

#66 Fix/team management fe
  src/components/TokenExpiredModal/useTokenExpiredModal.ts
  src/components/UserRow/index.tsx
  src/constants/constants.ts
  src/pages/TeamManagment/UserForm/index.tsx
  src/pages/TeamManagment/UserForm/useUserForm.tsx
  src/pages/TeamManagment/index.tsx
  src/pages/TeamManagment/styles.ts
  src/pages/TeamManagment/useFetchUsers.tsx
  src/pages/TeamManagment/useUserFilters.tsx
  src/utils/i18n.ts
Labels: bug, enhancement

#69 feat: resized pages and rows
  src/components/RoutesRow/index.tsx
  src/pages/CreateRoute/SecondStage/components/OrderManagementCard/styles.ts
  src/pages/CreateRoute/SecondStage/styles.ts
  src/pages/Orders/components/OrderItem/styles.ts
  src/pages/Orders/components/SortingRow/styles.ts
  src/pages/TeamManagment/styles.ts
  src/pages/components/CreateRouteBtns/styles.ts
  src/pages/components/CreateRouteProgressBar/styles.ts
Labels: bug

#70 + Create: custom map-pin
  src/assets/icons/map-pin.png
  src/components/CustomMapPin/index.tsx
  src/pages/CreateRoute/RouteManagement/components/Map/index.tsx
  src/pages/RouteDetails/components/Map/index.tsx
Labels: bug, enhancement, invalid

#72 Feat/documentation
  .env.example
  README.md
Labels: documentation
